#!/bin/sh
#
#  GRUB displays the boot menu at the next boot if it
#  believes that the previous boot failed. This script
#  informs it that the system booted successfully.
#  This script is called by the GDM init script (we are
#  assuming that if we reach GDM then the boot is
#  successful)

[ -s /boot/grub/grubenv ] || rm -f /boot/grub/grubenv
/usr/bin/grub-editenv /boot/grub/grubenv unset recordfail

exit 0
